/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overall system health
         * @description Returns overall system status including uptime and version.
         */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns alive status for container orchestrators.
         */
        get: operations["get_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns whether all dependencies are initialized and ready.
         */
        get: operations["get_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search academic literature
         * @description Search across configured academic literature databases.
         */
        post: operations["search_articles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search, download, process, and index articles
         * @description Runs the full ingest pipeline: search → download → process → index.
         */
        post: operations["ingest_articles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search and download articles without indexing
         * @description Search for articles and download PDFs without processing or indexing.
         */
        post: operations["search_and_download"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a research question
         * @description Query indexed documents with a natural language question. Uses RAG (retrieval-augmented generation) to answer from your document corpus.
         */
        post: operations["ask_question"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List indexed documents
         * @description Returns paginated list of indexed documents with metadata.
         */
        get: operations["list_documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get document details
         * @description Returns document metadata and chunks by ID.
         */
        get: operations["get_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get document chunks
         * @description Returns paginated chunks for a document.
         */
        get: operations["get_document_chunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summarize a document
         * @description Generate an LLM-powered summary of an indexed document.
         */
        get: operations["get_document_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find similar documents
         * @description Find and analyze documents similar to the specified document.
         */
        get: operations["get_similar_documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerResponse */
        AnswerResponse: {
            /**
             * Answer
             * @default
             */
            answer: string;
            /** Sources */
            sources?: string[];
            /** Citations */
            citations?: {
                [key: string]: unknown;
            }[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Llm Model
             * @default
             */
            llm_model: string;
            /**
             * Llm Provider
             * @default
             */
            llm_provider: string;
            /**
             * Llm Elapsed Ms
             * @default 0
             */
            llm_elapsed_ms: number;
        };
        /** ArticleResponse */
        ArticleResponse: {
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Doi
             * @default
             */
            doi: string;
            /**
             * Pmid
             * @default
             */
            pmid: string;
            /**
             * Pmcid
             * @default
             */
            pmcid: string;
            /** Authors */
            authors?: string[];
            /** Year */
            year?: number | null;
            /**
             * Journal
             * @default
             */
            journal: string;
            /**
             * Abstract
             * @default
             */
            abstract: string;
        };
        /** AskRequest */
        AskRequest: {
            /**
             * Question
             * @description Research question
             */
            question: string;
            /**
             * Llm Provider
             * @description LLM provider override
             */
            llm_provider?: string | null;
            /**
             * Temperature
             * @description LLM temperature
             */
            temperature?: number | null;
            /**
             * Max Tokens
             * @description Max tokens in response
             */
            max_tokens?: number | null;
        };
        /** AskResponse */
        AskResponse: {
            answer: components["schemas"]["AnswerResponse"];
            /** Chunks */
            chunks?: components["schemas"]["ChunkInfo"][];
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** ChunkInfo */
        ChunkInfo: {
            /**
             * Document Id
             * @default
             */
            document_id: string;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Heading
             * @default
             */
            heading: string;
        };
        /** ChunkListResponse */
        ChunkListResponse: {
            /** Items */
            items?: components["schemas"]["ChunkRecord"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** ChunkRecord */
        ChunkRecord: {
            /**
             * Chunk Id
             * @default
             */
            chunk_id: string;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Heading
             * @default
             */
            heading: string;
            /**
             * Chunk Index
             * @default 0
             */
            chunk_index: number;
        };
        /** DocumentDetailResponse */
        DocumentDetailResponse: {
            /**
             * Document Id
             * @default
             */
            document_id: string;
            metadata?: components["schemas"]["DocumentMetadata"];
            /** Chunks */
            chunks?: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * @default
             */
            created_at: string;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Items */
            items?: components["schemas"]["DocumentRecord"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** DocumentMetadata */
        DocumentMetadata: {
            /**
             * Title
             * @default
             */
            title: string;
            /** Authors */
            authors?: string[];
            /**
             * Source
             * @default
             */
            source: string;
            /** Year */
            year?: number | null;
            /**
             * Doi
             * @default
             */
            doi: string;
        };
        /** DocumentRecord */
        DocumentRecord: {
            /**
             * Document Id
             * @default
             */
            document_id: string;
            metadata?: components["schemas"]["DocumentMetadata"];
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            /**
             * Created At
             * @default
             */
            created_at: string;
        };
        /** DownloadRequest */
        DownloadRequest: {
            /**
             * Query
             * @description Search and download query
             */
            query: string;
            /**
             * Max Results
             * @description Maximum articles to download
             * @default 5
             */
            max_results: number;
        };
        /** DownloadResponse */
        DownloadResponse: {
            /** Articles */
            articles?: {
                [key: string]: unknown;
            }[];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
            /**
             * Uptime Seconds
             * @default 0
             */
            uptime_seconds: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** IngestDocumentResponse */
        IngestDocumentResponse: {
            /**
             * Document Id
             * @default
             */
            document_id: string;
            /**
             * Status
             * @default
             */
            status: string;
            /**
             * Chunks
             * @default 0
             */
            chunks: number;
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Query
             * @description Search and ingest query
             */
            query: string;
            /**
             * Max Results
             * @description Maximum articles to ingest
             * @default 5
             */
            max_results: number;
            /**
             * Download Dir
             * @description Custom download directory
             */
            download_dir?: string | null;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Documents */
            documents?: components["schemas"]["IngestDocumentResponse"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default alive
             */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Agent Ready
             * @default false
             */
            agent_ready: boolean;
            /**
             * Knowledge Base Ready
             * @default false
             */
            knowledge_base_ready: boolean;
            /**
             * Cache Ready
             * @default false
             */
            cache_ready: boolean;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Query
             * @description Search query
             */
            query: string;
            /**
             * Max Results
             * @description Maximum articles to return
             * @default 10
             */
            max_results: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Articles */
            articles?: components["schemas"]["ArticleResponse"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** SimilarResponse */
        SimilarResponse: {
            /**
             * Document Id
             * @default
             */
            document_id: string;
            /**
             * Analysis
             * @default
             */
            analysis: string;
            /** Related Documents */
            related_documents?: string[];
            /**
             * Llm Model
             * @default
             */
            llm_model: string;
            /**
             * Llm Provider
             * @default
             */
            llm_provider: string;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /**
             * Document Id
             * @default
             */
            document_id: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Llm Model
             * @default
             */
            llm_model: string;
            /**
             * Llm Provider
             * @default
             */
            llm_provider: string;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    get_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    search_articles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_articles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_and_download: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Agent is busy processing another request */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents: {
        parameters: {
            query?: {
                /** @description Filter by title */
                query?: string;
                /** @description Pagination cursor */
                cursor?: string | null;
                /** @description Items per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_chunks: {
        parameters: {
            query?: {
                /** @description Pagination cursor */
                cursor?: string | null;
                /** @description Items per page */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_similar_documents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
