"""Output format renderers for the Editorial Digest.

Supports: Web, Markdown, Newsletter, Telegram, Email
"""

from __future__ import annotations

from api.editorial.models import EditorialDigest, EditorialPaper


def render_markdown(digest: EditorialDigest) -> str:
    """Render the editorial digest as Markdown (newsletter-ready)."""
    lines: list[str] = []

    lines.append(f"# {digest.title}")
    lines.append("")
    lines.append(f"*{digest.subtitle}*" if digest.subtitle else "")
    lines.append(f"**{digest.date.isoformat()}**")
    lines.append("")
    lines.append(f"_{' · '.join(digest.executive_summary)}_")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Top Story
    if digest.top_story.paper:
        lines.append("## 📰 Top Story")
        lines.append("")
        lines.append(f"### {digest.top_story.headline}")
        lines.append("")
        lines.append(f"**Why it matters:** {digest.top_story.why_it_matters}")
        lines.append("")
        lines.append(f"**Clinical impact:** {digest.top_story.clinical_impact}")
        lines.append("")
        lines.append(f"*Source: {digest.top_story.paper.journal} — "
                      f"{', '.join(digest.top_story.paper.authors[:3])}*")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Clinical Takeaway
    lines.append("## 🏥 Today's Clinical Takeaway")
    lines.append("")
    lines.append(f"**{digest.top_story.specialist_comment}**")
    lines.append("")
    for action in digest.practice_impact:
        lines.append(f"- {action}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Controversies
    if digest.controversies:
        lines.append("## ⚡ Research Controversies")
        lines.append("")
        for c in digest.controversies:
            lines.append(f"### {c.title}")
            lines.append("")
            lines.append(f"- **Position A:** {c.position_a}")
            lines.append(f"- **Position B:** {c.position_b}")
            lines.append(f"- **Resolution:** {c.resolution}")
            lines.append("")
        lines.append("---")
        lines.append("")

    # Research Trends
    if digest.research_trends:
        lines.append("## 📊 Research Trends")
        lines.append("")
        for trend in digest.research_trends[:3]:
            emoji = "🟢" if trend.momentum == "emerging" else "🔵"
            lines.append(f"{emoji} **{trend.name}** ({trend.paper_count} papers, {trend.momentum})")
        lines.append("")
        lines.append("---")
        lines.append("")

    # All Papers
    lines.append(f"## 📚 All Papers ({digest.total_papers_reviewed})")
    lines.append("")
    for paper in digest.papers:
        badge = ""
        if paper.is_top_story:
            badge = "⭐ "
        elif paper.is_breaking:
            badge = "🔴 "
        lines.append(f"- {badge}{paper.title}")
        lines.append(f"  *{', '.join(paper.authors[:3])} — {paper.journal}*")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*Reading time: {digest.reading_time_minutes} minutes*")
    lines.append(f"*Generated by AI Editorial Engine*")

    return "\n".join(lines)


def render_telegram(digest: EditorialDigest) -> str:
    """Render a Telegram-optimized version (max 4096 chars)."""
    lines: list[str] = []

    lines.append(f"📰 *{digest.title}*")
    lines.append("")

    if digest.top_story.paper:
        lines.append(f"⭐ *TOP STORY*")
        lines.append(f"{digest.top_story.headline[:200]}")
        lines.append("")

    lines.append(f"📊 *{digest.total_papers_reviewed} papers reviewed*")
    lines.append("")

    for summary in digest.executive_summary:
        lines.append(f"• {summary[:200]}")
    lines.append("")

    if digest.controversies:
        lines.append("⚡ *Controversies:*")
        for c in digest.controversies[:2]:
            lines.append(f"  • {c.title[:100]}")
        lines.append("")

    lines.append("---")
    lines.append(f"👃 *ENT Editorial Engine*")

    return "\n".join(lines)


def render_email(digest: EditorialDigest) -> str:
    """Render an HTML email version."""
    md = render_markdown(digest)
    # Simple MD-to-HTML conversion for email
    html = md.replace("\n", "<br>\n")
    html = html.replace("## ", "<h2>") + "</h2>"
    html = html.replace("### ", "<h3>") + "</h3>"
    html = html.replace("**", "<strong>") + "</strong>"
    html = html.replace("*", "<em>") + "</em>"
    return f"<html><body>{html}</body></html>"


def render_newsletter(digest: EditorialDigest) -> str:
    """Render a full HTML newsletter."""
    md = render_markdown(digest)
    return (
        f"<!DOCTYPE html>\n<html>\n<head>\n"
        f"<meta charset='utf-8'>\n"
        f"<meta name='viewport' content='width=device-width'>\n"
        f"<title>{digest.title}</title>\n"
        f"</head>\n<body style='font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;'>\n"
        f"<div style='background: #f0f9ff; padding: 20px; border-radius: 8px;'>\n"
        f"{render_email(digest)}\n"
        f"</div>\n"
        f"<p style='color: #666; font-size: 12px; text-align: center;'>"
        f"AI-generated editorial digest. Clinical decisions should be based on "
        f"review of primary sources and clinical judgment."
        f"</p>\n"
        f"</body>\n</html>"
    )
